on:
   push:
     tags:
       - Problem_Ticket 
       paths: 
         -'**.csv'

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Code 
         uses: actions/checkout@v3
 
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
            python-version: ‘3.11’

       - name: Run Python Script
         run: | 
             python3 -m pip install requests
             python3 -m pip install json
             python3 -m pip install csv
             python3 creat_problem.py 
